import { DonationModel } from "../models/donation.model";
import { DonationDTO } from "../models/donation.model";
import { NeedService } from "./need.service";
import { InventoryService } from "./inventory.service";
import { NotificationService } from "./notification.service";

export class DonationService {
  static async createDonation(
    donationData: Omit<DonationDTO, "id">
  ): Promise<DonationDTO> {
    try {
      const need = await NeedService.getNeedById(donationData.needId);
      if (!need) {
        throw new Error("Need not found");
      }

      const donation = await DonationModel.create({
        ...donationData,
        status: "pending",
      });

      await NotificationService.createNewDonationNotification(
        need.userId,
        need.itemName,
        donationData.quantity,
        need.unit,
        donation.id!
      );

      return donation;
    } catch (error) {
      console.error("Error in donation creation:", error);
      throw error;
    }
  }

  static async getDonationById(id: number): Promise<DonationDTO | null> {
    try {
      const donation = await DonationModel.getById(id);
      if (!donation) {
        throw new Error("Donation not found");
      }
      return donation;
    } catch (error) {
      console.error("Error fetching donation:", error);
      throw error;
    }
  }

  static async getDonationsByDonor(donorId: number): Promise<DonationDTO[]> {
    return DonationModel.getByDonorId(donorId);
  }

  static async getDonationsByNeed(needId: number): Promise<DonationDTO[]> {
    return DonationModel.getByNeedId(needId);
  }

  static async updateDonationStatus(
    id: number,
    status: string
  ): Promise<DonationDTO> {
    const donation = await DonationModel.update(id, { status });

    if (donation.need) {
      if (status === "completed") {
        await InventoryService.updateInventoryFromDonation(
          donation.need.itemName,
          donation.quantity,
          donation.need.unit,
          donation.need.userId
        );

        await NotificationService.createDonationStatusNotification(
          donation.donorId,
          donation.need.itemName,
          donation.quantity,
          donation.need.unit,
          "completed",
          donation.id!
        );

        if (!donation.need.isAutoGenerated && donation.need.id) {
          const newCurrentQuantity =
            donation.need.currentQuantity + donation.quantity;
          await NeedService.updateNeed(donation.need.id, donation.need.userId, {
            currentQuantity: newCurrentQuantity,
          });

          if (newCurrentQuantity >= donation.need.requiredQuantity) {
            await NeedService.deleteNeed(
              donation.need.id,
              donation.need.userId
            );
          }
        }
      } else if (status === "rejected") {
        await NotificationService.createDonationStatusNotification(
          donation.donorId,
          donation.need.itemName,
          donation.quantity,
          donation.need.unit,
          "rejected",
          donation.id!
        );
      }
    }

    return donation;
  }

  static async deleteDonation(id: number): Promise<void> {
    await DonationModel.delete(id);
  }

  static async getCareHomeDonations(
    careHomeId: number
  ): Promise<DonationDTO[]> {
    return DonationModel.getByCareHomeId(careHomeId);
  }

  static async processBulkDonations(
    donations: Omit<DonationDTO, "id">[]
  ): Promise<DonationDTO[]> {
    const results: DonationDTO[] = [];

    for (const donationData of donations) {
      try {
        const donation = await this.createDonation(donationData);
        results.push(donation);
      } catch (error) {
        console.error("Failed to process donation:", error);
      }
    }

    return results;
  }
}
