import { InventoryItemDTO, InventoryModel } from "../models/inventory.model";
import { NeedService } from "./need.service";

export class InventoryService {
  static async getAllItems(userId: number): Promise<InventoryItemDTO[]> {
    if (!userId) {
      throw new Error("User ID is required");
    }
    return await InventoryModel.getAll(userId);
  }

  static async getItemById(
    id: number,
    userId: number
  ): Promise<InventoryItemDTO | null> {
    return await InventoryModel.getById(id, userId);
  }

  static async createItem(
    itemData: Omit<InventoryItemDTO, "id">
  ): Promise<InventoryItemDTO> {
    const newItem = await InventoryModel.create(itemData);

    await this.checkAndGenerateNeeds(newItem, newItem.userId);

    return newItem;
  }

  static async updateItem(
    id: number,
    userId: number,
    itemData: Partial<InventoryItemDTO>
  ): Promise<InventoryItemDTO> {
    const updatedItem = await InventoryModel.update(id, userId, itemData);

    if (
      itemData.stockLevel !== undefined ||
      itemData.reorderLevel !== undefined
    ) {
      await this.checkAndGenerateNeeds(updatedItem, userId);
    }

    return updatedItem;
  }

  static async bulkUpdateItems(
    updates: Array<{ id: number; stockLevel: number }>,
    userId: number
  ): Promise<void> {
    for (const update of updates) {
      await this.updateItem(update.id, userId, {
        stockLevel: update.stockLevel,
      });
    }
  }

  static async deleteItem(
    id: number,
    userId: number
  ): Promise<InventoryItemDTO> {
    return await InventoryModel.delete(id, userId);
  }

  static async searchItems(
    query: string,
    userId: number
  ): Promise<InventoryItemDTO[]> {
    return await InventoryModel.search(query, userId);
  }

  static async updateInventoryFromDonation(
    itemName: string,
    quantity: number,
    unit: string,
    userId: number
  ): Promise<void> {
    try {
      const allItems = await InventoryModel.getAll(userId);
      const item = allItems.find(
        (i) => i.itemName === itemName && i.unit === unit
      );

      if (item && item.id) {
        const newStockLevel = item.stockLevel + quantity;
        await InventoryModel.update(item.id, userId, {
          stockLevel: newStockLevel,
        });

        await this.checkAndGenerateNeeds(
          { ...item, stockLevel: newStockLevel },
          userId
        );
      } else {
        await InventoryModel.create({
          itemName,
          category: "Donation",
          stockLevel: quantity,
          reorderLevel: 0,
          unit,
          userId,
        });
      }
    } catch (error) {
      console.error("Error updating inventory from donation:", error);
      throw error;
    }
  }

  static async checkAndGenerateNeeds(
    item: InventoryItemDTO,
    userId: number
  ): Promise<void> {
    if (item.stockLevel < item.reorderLevel) {
      const shortage = item.reorderLevel - item.stockLevel;

      try {
        const allNeeds = await NeedService.getAllNeeds(userId);
        const existingNeed = allNeeds.find(
          (n) => n.itemName === item.itemName && n.unit === item.unit
        );

        if (existingNeed && existingNeed.id) {
          await NeedService.updateNeed(existingNeed.id, userId, {
            requiredQuantity: shortage,
            currentQuantity: 0,
            urgencyLevel: this.calculateUrgency(
              item.stockLevel,
              item.reorderLevel
            ),
          });
        } else {
          await NeedService.createNeed({
            itemName: item.itemName,
            requiredQuantity: shortage,
            currentQuantity: 0,
            category: item.category,
            urgencyLevel: this.calculateUrgency(
              item.stockLevel,
              item.reorderLevel
            ),
            unit: item.unit,
            userId,
            isAutoGenerated: true,
          });
        }
      } catch (error) {
        console.error("Error generating need:", error);
      }
    } else {
      const allNeeds = await NeedService.getAllNeeds(userId);
      const autoNeed = allNeeds.find(
        (n) =>
          n.itemName === item.itemName &&
          n.unit === item.unit &&
          n.isAutoGenerated
      );

      if (autoNeed && autoNeed.id) {
        await NeedService.deleteNeed(autoNeed.id, userId);
      }
    }
  }

  static async getLowStockItems(userId: number): Promise<InventoryItemDTO[]> {
    const items = await this.getAllItems(userId);
    return items.filter((item) => item.stockLevel < item.reorderLevel);
  }

  private static calculateUrgency(
    stockLevel: number,
    reorderLevel: number
  ): "High" | "Medium" | "Low" {
    if (reorderLevel === 0) return "Medium";

    const percentage = (stockLevel / reorderLevel) * 100;

    if (percentage < 20) return "High";
    if (percentage < 50) return "Medium";
    return "Low";
  }
}
