import { InventoryItemDTO, InventoryModel } from "../models/inventory.model";
import { NeedService } from "./need.service";
import { NotificationService } from "./notification.service";

export class InventoryService {
  static async getAllItems(userId: number): Promise<InventoryItemDTO[]> {
    if (!userId) {
      throw new Error("User ID is required");
    }
    return await InventoryModel.getAll(userId);
  }

  static async getItemById(
    id: number,
    userId: number
  ): Promise<InventoryItemDTO | null> {
    return await InventoryModel.getById(id, userId);
  }

  static async createItem(
    itemData: Omit<InventoryItemDTO, "id">
  ): Promise<InventoryItemDTO> {
    const existingItem = await InventoryModel.getByNameAndUser(
      itemData.itemName, 
      itemData.userId
    );

    if (existingItem) {
      const updatedStockLevel = existingItem.stockLevel + itemData.stockLevel;
      const updatedItem = await InventoryModel.update(
        existingItem.id!,
        itemData.userId,
        {
          ...itemData,
          stockLevel: updatedStockLevel
        }
      );

      await this.checkAndGenerateNeeds(updatedItem, updatedItem.userId);
      return updatedItem;
    } else {
      const newItem = await InventoryModel.create(itemData);
      await this.checkAndGenerateNeeds(newItem, newItem.userId);
      return newItem;
    }
  }

  static async updateItem(
    id: number,
    userId: number,
    itemData: Partial<InventoryItemDTO>
  ): Promise<InventoryItemDTO> {
    const updatedItem = await InventoryModel.update(id, userId, itemData);

    if (
      itemData.stockLevel !== undefined ||
      itemData.reorderLevel !== undefined
    ) {
      await this.checkAndGenerateNeeds(updatedItem, userId);
    }

    return updatedItem;
  }

  static async bulkUpdateItems(
    updates: Array<{ id: number; stockLevel: number }>,
    userId: number
  ): Promise<void> {
    for (const update of updates) {
      await this.updateItem(update.id, userId, {
        stockLevel: update.stockLevel,
      });
    }
  }

  static async deleteItem(
    id: number,
    userId: number
  ): Promise<InventoryItemDTO> {
    return await InventoryModel.delete(id, userId);
  }

  static async searchItems(
    query: string,
    userId: number
  ): Promise<InventoryItemDTO[]> {
    return await InventoryModel.search(query, userId);
  }

  static async updateInventoryFromDonation(
    itemName: string,
    quantity: number,
    unit: string,
    userId: number
  ): Promise<void> {
    try {
      const existingItem = await InventoryModel.getByNameAndUser(itemName, userId);

      if (existingItem && existingItem.id) {
        const newStockLevel = existingItem.stockLevel + quantity;
        await InventoryModel.update(existingItem.id, userId, {
          stockLevel: newStockLevel,
        });

        await this.checkAndGenerateNeeds(
          { ...existingItem, stockLevel: newStockLevel },
          userId
        );
      } else {
        await InventoryModel.create({
          itemName,
          category: "Donation",
          stockLevel: quantity,
          reorderLevel: 0,
          unit,
          userId,
        });
      }
    } catch (error) {
      console.error("Error updating inventory from donation:", error);
      throw error;
    }
  }

  static async checkAndGenerateNeeds(
    item: InventoryItemDTO,
    userId: number
  ): Promise<void> {
    if (item.stockLevel < item.reorderLevel) {
      const shortage = item.reorderLevel - item.stockLevel;

      try {
        const allNeeds = await NeedService.getAllNeeds(userId);
        const existingNeed = allNeeds.find(
          (n) => n.itemName === item.itemName && n.unit === item.unit
        );

        if (existingNeed && existingNeed.id) {
          await NeedService.updateNeed(existingNeed.id, userId, {
            requiredQuantity: shortage,
            currentQuantity: 0,
            urgencyLevel: this.calculateUrgency(
              item.stockLevel,
              item.reorderLevel
            ),
          });
        } else {
          await NeedService.createNeed({
            itemName: item.itemName,
            requiredQuantity: shortage,
            currentQuantity: 0,
            category: item.category,
            urgencyLevel: this.calculateUrgency(
              item.stockLevel,
              item.reorderLevel
            ),
            unit: item.unit,
            userId,
            isAutoGenerated: true,
          });
        }

        await NotificationService.createLowStockNotification(
          userId,
          item.itemName,
          item.stockLevel,
          item.reorderLevel,
          item.unit,
          item.id!
        );
      } catch (error) {
        console.error("Error generating need:", error);
      }
    } else {
      const allNeeds = await NeedService.getAllNeeds(userId);
      const autoNeed = allNeeds.find(
        (n) =>
          n.itemName === item.itemName &&
          n.unit === item.unit &&
          n.isAutoGenerated
      );

      if (autoNeed && autoNeed.id) {
        await NeedService.deleteNeed(autoNeed.id, userId);
      }
    }
  }

  static async getLowStockItems(userId: number): Promise<InventoryItemDTO[]> {
    const items = await this.getAllItems(userId);
    return items.filter((item) => item.stockLevel < item.reorderLevel);
  }

  private static calculateUrgency(
    stockLevel: number,
    reorderLevel: number
  ): "High" | "Medium" | "Low" {
    if (reorderLevel === 0) return "Medium";

    const percentage = (stockLevel / reorderLevel) * 100;

    if (percentage < 20) return "High";
    if (percentage < 50) return "Medium";
    return "Low";
  }

  static async bulkImportItems(
    items: Omit<InventoryItemDTO, "id">[],
    userId: number
  ): Promise<InventoryItemDTO[]> {
    const createdItems: InventoryItemDTO[] = [];
    
    for (const item of items) {
      const existingItem = await InventoryModel.getByNameAndUser(item.itemName, userId);
      
      if (existingItem) {
        const updatedStockLevel = existingItem.stockLevel + item.stockLevel;
        const updatedItem = await InventoryModel.update(
          existingItem.id!,
          userId,
          {
            ...item,
            stockLevel: updatedStockLevel
          }
        );
        createdItems.push(updatedItem);
        await this.checkAndGenerateNeeds(updatedItem, userId);
      } else {
        const newItem = await InventoryModel.create({
          ...item,
          userId,
        });
        createdItems.push(newItem);
        await this.checkAndGenerateNeeds(newItem, userId);
      }
    }
    return createdItems;
  }

  static async bulkDeleteItems(userId: number): Promise<void> {
    await InventoryModel.bulkDelete(userId);
  }
}