-- AlterTable
ALTER TABLE "inventory" ADD COLUMN     "unit" TEXT NOT NULL DEFAULT 'units';

-- AlterTable
ALTER TABLE "needs" ADD COLUMN     "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "unit" TEXT NOT NULL DEFAULT 'units';
