import { PrismaClient, Need } from "@prisma/client";

const prisma = new PrismaClient();

export interface NeedItemDTO {
  id?: number;
  itemName: string;
  requiredQuantity: number;
  currentQuantity: number;
  category: string;
  urgencyLevel: "High" | "Medium" | "Low";
  unit: string;
  userId: number;
  isAutoGenerated: boolean;
}

function toDTO(need: Need): NeedItemDTO {
  return {
    id: need.id,
    itemName: need.itemName,
    requiredQuantity: need.requiredQuantity,
    currentQuantity: need.currentQuantity,
    category: need.category,
    urgencyLevel: need.urgencyLevel as "High" | "Medium" | "Low",
    unit: need.unit,
    userId: need.userId,
    isAutoGenerated: need.isAutoGenerated,
  };
}

export const NeedModel = {
  async getAll(userId: number): Promise<NeedItemDTO[]> {
    const items = await prisma.need.findMany({
      where: { userId },
    });
    return items.map(toDTO);
  },

  async getById(id: number): Promise<NeedItemDTO | null> {
    const item = await prisma.need.findUnique({
      where: { id },
    });
    return item ? toDTO(item) : null;
  },

  async create(item: Omit<NeedItemDTO, "id">): Promise<NeedItemDTO> {
    const createdItem = await prisma.need.create({
      data: {
        ...item,
        isAutoGenerated: item.isAutoGenerated || false,
      },
    });
    return toDTO(createdItem);
  },

  async update(
    id: number,
    userId: number,
    item: Partial<NeedItemDTO>
  ): Promise<NeedItemDTO> {
    const updatedItem = await prisma.need.update({
      where: { id, userId },
      data: item,
    });
    return toDTO(updatedItem);
  },

  async delete(id: number, userId: number): Promise<void> {
    await prisma.need.delete({
      where: { id, userId },
    });
  },

  async getUrgentNeeds(page: number = 1, limit: number = 20): Promise<{
    needs: any[];
    totalCount: number;
    currentPage: number;
    totalPages: number;
    hasMore: boolean;
  }> {
    const skip = (page - 1) * limit;

    const urgentNeeds = await prisma.need.findMany({
      where: {
        user: {
          role: "CAREHOME",
          isVerified: true,
        },
        urgencyLevel: "High",
      },
      include: {
        user: {
          select: {
            id: true,
            name: true,
            category: true,
            address: true,
          },
        },
      },
      skip,
      take: limit,
      orderBy: {
        createdAt: 'desc',
      },
    });

    const totalUrgentNeeds = await prisma.need.count({
      where: {
        user: {
          role: "CAREHOME",
          isVerified: true,
        },
        urgencyLevel: "High",
      },
    });

    const simplifiedNeeds = urgentNeeds.map(need => ({
      id: need.id,
      itemName: need.itemName,
      requiredQuantity: need.requiredQuantity,
      category: need.category,
      urgencyLevel: need.urgencyLevel,
      unit: need.unit,
      careHomeId: need.userId,
      careHomeName: need.user.name,
      careHomeCategory: need.user.category,
      careHomeAddress: need.user.address,
    }));

    return {
      needs: simplifiedNeeds,
      totalCount: totalUrgentNeeds,
      currentPage: page,
      totalPages: Math.ceil(totalUrgentNeeds / limit),
      hasMore: skip + urgentNeeds.length < totalUrgentNeeds,
    };
  },
};
